version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: justas
      POSTGRES_PASSWORD: justas
      POSTGRES_DB: trello
    ports:
      - "5432"
    volumes:
      - trello:/var/lib/postgresql/data

  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgres://justas:justas@postgres:5432/trello
      MONGO_URI: mongodb://mongo:27017
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  trello:
  mongo_data:
