version: "3.8"

services:
  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: justas
      POSTGRES_PASSWORD: justas
      POSTGRES_DB: trello
    ports:
      - "5432:5432"
    volumes:
      - trello:/var/lib/postgresql/data

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:latest
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./config/redis/redis.crt:/usr/local/etc/redis/redis.crt
      - ./config/redis/redis.key:/usr/local/etc/redis/redis.key
      - ./config/redis/ca.crt:/usr/local/etc/redis/ca.crt
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6380:6380"

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      DATABASE_URL: postgres://justas:justas@postgres:5432/trello
      MONGO_URI: mongodb://root:example@mongo:27017
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6380
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
      - redis

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      API_PROXY_PASS: http://server:3000
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  trello:
  mongodata:
